In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv(
    r"C:\Users\omgow\OneDrive\Desktop\MSIS\AML_LAB\project_LAB_3\data\bestsellers with categories.csv"
)

In [5]:
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [6]:
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [7]:
df.tail()

,Name,Author,User Rating,Reviews,Price,Year,Genre
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

In [9]:
df.shape

(550, 7)

In [10]:
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [11]:
df.dtypes

Name            object
Author          object
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre           object
dtype: object

In [12]:
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [13]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [14]:
df.duplicated().sum()

0

In [16]:
# Select independent variables
x = df[
    ["Name", "Author", "User Rating", "Reviews", "Price", "Year"]
].values

# Select dependent variable
y = df["Genre"].values

In [17]:
y

array(['Non Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction'], dtype=object)

In [18]:
#taking care of missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:,2:5])
x[:,2:5] = imputer.transform(x[:,2:5])
x

array([['10-Day Green Smoothie Cleanse', 'JJ Smith', 4.7, 17350.0, 8.0,
        2016],
       ['11/22/63: A Novel', 'Stephen King', 4.6, 2052.0, 22.0, 2011],
       ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson',
        4.7, 18979.0, 15.0, 2018],
       ...,
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2017],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2018],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2019]], dtype=object)

In [19]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,0] = LabelEncoder().fit_transform(x[:,0])
x[:,1] = LabelEncoder().fit_transform(x[:,1])
print(x)

[[0 114 4.7 17350.0 8.0 2016]
 [1 219 4.6 2052.0 22.0 2011]
 [2 134 4.7 18979.0 15.0 2018]
 ...
 [350 121 4.7 14331.0 8.0 2017]
 [350 121 4.7 14331.0 8.0 2018]
 [350 121 4.7 14331.0 8.0 2019]]

In [27]:
#encoding the dependent variable
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [20]:
#encoding independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#One hot encoding the year col(index 5) after label encoding name & author(indices 0,1)
ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(categories='auto'), [5])], remainder='passthrough')
x = ct.fit_transform(x)

x.astype(int)

array([[    0,     0,     0, ...,     4, 17350,     8],
       [    0,     0,     1, ...,     4,  2052,    22],
       [    0,     0,     0, ...,     4, 18979,    15],
       ...,
       [    0,     0,     0, ...,     4, 14331,     8],
       [    0,     0,     0, ...,     4, 14331,     8],
       [    0,     0,     0, ...,     4, 14331,     8]])

In [21]:
#split data into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [22]:
x_test

array([[0.0, 0.0, 0.0, ..., 4.9, 12619.0, 8.0],
       [0.0, 0.0, 0.0, ..., 4.4, 1201.0, 40.0],
       [1.0, 0.0, 0.0, ..., 4.7, 5505.0, 18.0],
       ...,
       [0.0, 0.0, 0.0, ..., 4.6, 27098.0, 15.0],
       [0.0, 0.0, 0.0, ..., 4.8, 6247.0, 10.0],
       [0.0, 0.0, 0.0, ..., 4.8, 21625.0, 9.0]], dtype=object)

In [23]:
x_test.astype(int)

array([[    0,     0,     0, ...,     4, 12619,     8],
       [    0,     0,     0, ...,     4,  1201,    40],
       [    1,     0,     0, ...,     4,  5505,    18],
       ...,
       [    0,     0,     0, ...,     4, 27098,    15],
       [    0,     0,     0, ...,     4,  6247,    10],
       [    0,     0,     0, ...,     4, 21625,     9]])

In [24]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [25]:
x_train

array([[-0.31186032, -0.30745303,  3.16227766, ..., -0.09152563,
        -0.5504203 , -0.73426458],
       [-0.31186032, -0.30745303, -0.31622777, ...,  0.80339168,
         0.11215336,  3.76354094],
       [-0.31186032, -0.30745303, -0.31622777, ...,  0.35593302,
         0.18449224, -0.44717061],
       ...,
       [-0.31186032, -0.30745303, -0.31622777, ..., -0.09152563,
         0.98501446, -0.44717061],
       [-0.31186032,  3.25252938, -0.31622777, ..., -0.98644295,
        -0.98394888, -0.16007664],
       [-0.31186032, -0.30745303, -0.31622777, ...,  1.25085033,
         0.62567529, -0.44717061]])